projectboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),

    path('projects/', views.ProjectListView.as_view(), name='projects'),
    path('project/<int:pk>', views.project_detail_view, name='project-detail'),
    path('project/<int:pk>/additem', views.project_detail_add_item, name='project-detail-add-item'),
    path('project/<int:pk>/addcomment', views.project_detail_add_comment, name='project-detail-add-comment'),
    path('project/<int:pk>/sendmessage', views.project_detail_send_message, name='project-detail-send-message'),
    path('project/<int:pk>/vote', views.project_detail_vote, name='project-detail-vote'),

    path('project/<int:pk>/delete-checklist-items/', views.delete_checklist_items, name='project-delete-checklist-items'),

    path('projects/<int:pk>/leave/', views.leave_project, name='project-leave'),

    path('sendinvite/', views.invite_user, name='invite-user'),


    path('myprojects/', views.MyProjectsListView.as_view(), name='my-projects'),

    path('project/create/', views.ProjectCreate.as_view(), name='project-create'),
    path('project/<int:pk>/update/', views.ProjectUpdate.as_view(), name='project-update'),
    path('project/<int:pk>/delete/', views.ProjectDelete.as_view(), name='project-delete'),

    path('invites/', views.project_invites, name='project-invites'),
    path('invites/<int:invite_pk>/', views.handle_invite, name='accept-invite'),
]



reforum/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView 
from django.urls import include # dynamically including all projectboard app urls in the root project 
from django.conf import settings
from django.conf.urls.static import static

from projectboard import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('projectboard/', include('projectboard.urls')),
    path('', RedirectView.as_view(url='projectboard/', permanent=True)), # redirect user to /projectboard by default
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


projectboard/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from datetime import datetime

class Project(models.Model):

    author_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name="author_user")
 
    name = models.CharField(max_length=100, help_text='')
    description = models.TextField(max_length=1000)
    post_date = models.DateTimeField(auto_now_add=True, help_text = "The time the project was created.")
    held_date = models.DateTimeField(help_text = "")

    lat = models.DecimalField(max_digits=22, decimal_places=16, blank=False, null=False)
    long = models.DecimalField(max_digits=22, decimal_places=16, blank=False, null=False)

    # project has many members, members may be in multiple projects
    # no need for "through" table as we're not saving any additional data (such as when the user joined the chat)
    member_users = models.ManyToManyField(settings.AUTH_USER_MODEL, help_text="Users taking part in the project", related_name="member_users")
    
    class Meta:
        ordering = ['-post_date']

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('project-detail', args=[str(self.id)])

    def points(self):
        pos_votes =  self.vote_set.filter(project = self, is_positive = True).count()
        neg_votes = self.vote_set.filter(project = self, is_positive = False).count()
        return pos_votes - neg_votes
    
    # def save_model(self, request, instance, form, change):
    #     user = request.user 
    #     instance = form.save(commit=False)
    #     if not change or not instance.author_user:
    #         instance.author_user = user
    #     instance.save()
    #     form.save_m2m()
    #     return instance


    @property
    def is_active(self):
        return bool(self.held_date and datetime.today().timestamp() <= self.held_date.timestamp())
    




class ChecklistItem(models.Model):

    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True)
    description = models.CharField(max_length=100, help_text='Enter the checklist item description.') 
    is_checked = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.description}'

class Vote(models.Model):

    voter = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True)
    is_positive = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.voter} {"up" if self.is_positive else "down"}voted \"{self.project.name}\"'


class Comment(models.Model):

    commenter = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True)
    text = models.TextField(max_length=1000)
    post_date = models.DateTimeField(auto_now_add=True, help_text = "The time the comment was created.")

    def __str__(self):
        length = 90
        return f'{self.commenter} commented \"{self.text[0:length]}{"" if len(self.text)<length else "..."}\" on \"{self.project.name}\"'

    def get_absolute_url(self):
        return reverse("commentdetail", kwargs={"pk": self.pk})


class Invite(models.Model):
    inviting_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name="inviting_user")
    invited_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name="invited_user")
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True)
    accepted = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.inviting_user} invited \"{self.invited_user}\" to \"{self.project.name}\"'

    def accept_invite(self):
        if not self.accepted:
            self.accepted = True
            self.project.member_users.add(self.invited_user)
            self.save()


class Message(models.Model):

    poster = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True)
    post_date = models.DateTimeField(auto_now_add=True, help_text = "The time the comment was created.")
    text = models.TextField(max_length=1000)

    class Meta:
        ordering = ['post_date']

    def __str__(self):
        length = 90
        return f'{self.poster} wrote \"{self.text[0:length]}{"" if len(self.text)<length else "..."}\" on \"{self.project.name}\"'

projectboard/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.models import User
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CheckDeleteForm, CheckForm, InviteForm, ItemForm, ProjectModelForm, CommentForm, MessageForm, VoteForm
from .models import Project, Invite, Comment, ChecklistItem, Message, Vote
from .mixins import UserIsProjectOwnerMixin
from django.db.models import Q
from projectboard.forms import CustomUserCreationForm
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth import login

def index(request):
    
    n_projects = Project.objects.all().count()
    n_users = User.objects.all().count()
    n_visits = request.session.get('n_visits', 0)
    request.session['n_visits'] = n_visits + 1

    # sending data as context to the html template
    context = {
        'n_projects' : n_projects,
        'n_users' : n_users,
        'n_visits' : n_visits
    }

    return render(request, 'index.html', context=context)



class ProjectListView(generic.ListView):
    model = Project
    paginate_by=10
    template_name = 'projectboard/project_list.html'
    def get_queryset(self):
        query = self.request.GET.get('q')
        print(f"Search Query: {query}")
        if query:
            return Project.objects.filter(
                Q(name__icontains=query) |
                Q(description__icontains=query)
            )
        else:
            return Project.objects.all()

# changed to function based view as I found it much easier to work with compared to overriding class functions
def project_detail_view(request, pk):
    context = {}
    #votes = Vote.objects.all()
    project = Project.objects.get(id=pk)

    # pos_votes =  votes.filter(project = project, is_positive = True).count()
    # neg_votes = votes.filter(project = project, is_positive = False).count()
    # points = pos_votes - neg_votes

    item_form = ItemForm()
    list_form = CheckForm(project = project)
    comment_form = CommentForm()
    message_form = MessageForm()
    vote_form = VoteForm()
    
    # context["points"] = points
    context["project"] = project

    if request.method == "POST":
        list_form = CheckForm(project, request.POST)
        #print("clicked")
        if list_form.is_valid():
            #print("valid")
            #print(str(list_form.data))
            data = list_form.cleaned_data
            
            for checkitem in ChecklistItem.objects.filter(project = project):
                if checkitem in data["checks"]:
                    checkitem.is_checked=True
                else:
                    checkitem.is_checked=False
                checkitem.save()
            return HttpResponseRedirect(f'{project.id}#checklist') # focus back onto checklist part of page
        #else:
            #print(request.POST)    
            #print(list_form.errors)
    context["forms"] = {"item": item_form, "list": list_form, "comment": comment_form, "message": message_form, "vote" : vote_form}
    return render(request, 'projectboard/project_detail.html', context=context)


def delete_checklist_items(request, pk):
    project = get_object_or_404(Project, id=pk)
    form = CheckDeleteForm(project=project)

    if request.method == "POST":
        form = CheckDeleteForm(project, request.POST)
        if form.is_valid():
            data = form.cleaned_data
            for checkitem in ChecklistItem.objects.filter(project=project):
                if checkitem in data["checks"]:
                    checkitem.delete()

            redirect_url = f"/projectboard/project/{pk}#checklist"
            return redirect(redirect_url)

    context = {"project": project, "form": form}
    return render(request, 'projectboard/delete_checklist_items.html', context=context)

def project_detail_add_item(request, pk):
    project = get_object_or_404(Project, id=pk)

    if request.method == "POST":
        form = ItemForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            # process
            item = ChecklistItem(
                project = project,
                description = data["description"],
                is_checked = False,
                )
            item.save()
    redirect_url = f"/projectboard/project/{pk}#checklist"
    return redirect(redirect_url)

def project_detail_add_comment(request, pk):
    project = get_object_or_404(Project, id=pk)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            # process
            item = Comment(
                project = project,
                text = data["text"],
                commenter = request.user
                )
            item.save()
    redirect_url = f"/projectboard/project/{pk}#commentlist"
    return redirect(redirect_url)



def project_detail_send_message(request, pk):
    project = get_object_or_404(Project, id=pk)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            # process
            item = Message(
                project = project,
                text = data["text"],
                poster = request.user
                )
            item.save()

    redirect_url = f"/projectboard/project/{pk}#chat"
    return redirect(redirect_url)


def project_detail_vote(request, pk):
    project = Project.objects.get(pk=pk)
    user = request.user

    try:
        vote = Vote.objects.get(voter=user, project=project)
    except Vote.DoesNotExist:
        vote = None

    if request.method == 'POST':
        form = VoteForm(request.POST)

        if form.is_valid():
            vote_action = form.cleaned_data['vote_action']

            if vote_action == 'upvote':
                if not vote:
                    Vote.objects.create(voter=user, project=project, is_positive=True)
                else:
                    vote.is_positive = True
                    vote.save()

            elif vote_action == 'downvote':
                if not vote:
                    Vote.objects.create(voter=user, project=project, is_positive=False)
                else:
                    vote.is_positive = False
                    vote.save()

            elif vote_action == 'reset':
                if vote:
                    vote.delete()

    return redirect("project-detail", project.id)


def invite_user(request):
    if request.method == 'POST':
        form = InviteForm(request.POST, user=request.user.id)
        if form.is_valid():
            invite = form.save(commit=False)
            invite.inviting_user = request.user
            invite.save()
            return redirect("my-projects")
    else:
        form = InviteForm(user=request.user.id)

    return render(request, 'projectboard/invite_form.html', {'form': form})


def project_invites(request):
    user_invites = Invite.objects.filter(invited_user=request.user.id, accepted=False)
    return render(request, 'projectboard/project_invites.html', {'user_invites': user_invites})


def handle_invite(request, invite_pk):
    invite = get_object_or_404(Invite, id=invite_pk, invited_user=request.user.id, accepted=False)

    if request.method == 'POST':
        action = request.POST.get('action')

        if action == 'accept':
            invite.accept_invite()
        elif action == 'delete':
            invite.delete()

    return redirect('project-invites')


def leave_project(request, pk):
    project = get_object_or_404(Project, id=pk)
    #print("hello!...")
    if request.method == 'POST':
        #print("post...")
        if request.user == project.author_user:
            #print("user is author")
            # if the author is trying to leave, do nothing
            return redirect('project-detail', project.id)
        # else remove him from members
        #print("removing user...")
        project.member_users.remove(request.user)

    return redirect('project-detail', project.id)


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
    else:
        form = CustomUserCreationForm()
    
    return render(request, 'registration/register.html', {'form': form})

# class-based project  list view and project creation views

class MyProjectsListView(LoginRequiredMixin,generic.ListView):
    model = Project
    template_name = 'projectboard/my_projects_list.html'
    paginate_by = 10

    def get_queryset(self):
        return (
            Project.objects.filter(member_users=self.request.user)
            .order_by('-held_date')
        )


class ProjectCreate(LoginRequiredMixin, CreateView):

    model = Project
    # widgets only work and can be defined with an explicit form, not overridden here
    form_class = ProjectModelForm
    def form_valid(self, form):
        # set author_user field to current user
        form.instance.author_user = self.request.user
        # save form to create Project instance and get id
        response = super().form_valid(form)

        # clear existing member_users and add the current user
        self.object.member_users.clear()
        self.object.member_users.add(self.request.user)
        return response
        

projectboard/templates/projectboard/delete_checklist_items.html
{% extends 'base.html' %}
{% block content %}
  <h2>Delete checklist items:</h2>
  <form action="" method="post">
    {% csrf_token %}
    {% for item in form.checks %}
      <li style="list-style-type: none; padding-top: 1.5%">
        {{ item }}
    </li>
    {% endfor %}
    <button type="submit">Delete selected items</button>
  </form>
{% endblock %}

projectboard/templates/projectboard/invite_form.html
{% extends 'base.html' %}
{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <input type="submit" value="Submit" />
  </form>
{% endblock %}

projectboard/templates/projectboard/my_projects_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Projects you've joined</h1>

  {% if project_list %}
    <ul>
      {% for project in project_list %}
        <li class="project">
          <div class="projectcore">
            <strong><a class="linkbutton" href="{{project.author_user.get_absolute_url}}">{{project.author_user}}</a>: </strong><a class="linkbutton" href="{{ project.get_absolute_url }}">{{ project.name }}, at {{project.held_date}}</a>
            <p>
              <i>"{{ project.description }}"</i>
            </p>
          </div>
          {% if project.checklistitem_set.all %}
            <!-- <div class = "checklist"> -->
            <ul class="checklist">
              {% for item in project.checklistitem_set.all %}
                <li>
                  {% if item.is_checked %}
                    ☑
                  {% else %}
                    ☐
                  {% endif %} {{ item }}
                </li>
              {% endfor %}
            </ul>
            <!-- </div> -->
          {% else %}

          {% endif %}
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>You haven't joined any projects yet. Check the invites tab or ask to join a project.</p>
  {% endif %}
{% endblock %}

projectboard/templates/projectboard/project_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete project: {{ project }}</h1>
  <p>Are you sure you want to delete the project?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" action="" value="Yes, delete." />
  </form>
{% endblock %}

projectboard/templates/projectboard/project_detail.html
{% extends 'base.html' %}

{% block content %}

  <div class="projectdetail">
    <h1>{{ project.name }} ({{ project.points }} point{{ project.points|pluralize }})</h1>
  
    <div class="projectcore">
      <strong><a class="linkbutton" href="{{ project.author_user.get_absolute_url }}">{{ project.author_user }}</a></strong>
      posted on {{ project.post_date }}
      <br />
      <ul style="list-style-type: none; font-size: 20px; margin-left: -3%;">
      {%if user == project.author_user%}
      
      <li>
        <a href="{% url 'project-update' project.id %}" class="linkbutton">Edit project</a>
      </li>
      <li>
        <a href="{% url 'project-delete' project.id %}" class="linkbutton">Delete project</a>
      </li>
    
      {%endif%}

      {% if user in project.member_users.all%}
        {% if request.user == project.author_user %}
        {%else%}
          <li>
            <form method="post" action="{% url 'project-leave' project.id %}">
              {% csrf_token %}
              <button type="submit" class="linkbutton">Leave project</button>
            </form>
          </li>
        {% endif %}
      {% endif %}
    </ul>
      {% comment %} {% if user in project.member_users.all %}
        <ul style="list-style-type: none; font-size: 20px; margin-left: -3%;">
          <li>
            <a href="{% url 'invite-user'%}" class="linkbutton">Invite users</a>
          </li>
        </ul> {% endcomment %}
        {% if user.is_authenticated%}
      <div style="position: absolute; top: 5%; right:5%">
      <form method="post" action="{% url 'project-detail-vote' project.id %}">
          {% csrf_token %}
          {{ forms.vote }}
          <button type="submit">Submit</button>
      </form>
    </div>
      {% endif %}Held <strong>
        {{ project.held_date }}{% if project.is_active %}

        {% else %}
          (ENDED)
        {% endif %}
      </strong>
      {% comment %} {% if project.lat and project.long %}
        at
        {{ project.lat }}, {{ project.long }}
      {% endif %} {% endcomment %}
      <hr />
      <h2>Description</h2>
      {{ project.description }}
      <h2>Location</h2>
      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCz__n-yYuMyDgr5OTwWpUQC6m9PbhxCLY&libraries=places&callback=Function.prototype"></script>
      <script>
        function initMap() {
            var latInput = document.getElementById('map-lat');
            var longInput = document.getElementById('map-long');
    
            var projectLocation = { lat: {{ project.lat }}, lng: {{ project.long }} };

            var map = new google.maps.Map(document.getElementById('project-map'), {
                center: projectLocation,
                zoom: 11
            });
    
            var marker;
  
              marker = new google.maps.Marker({
                  map: map,
                  position: projectLocation,
                  draggable: false
              });

      }
      google.maps.event.addDomListener(window, 'load', initMap);
      </script>
    
      <div id="project-map"></div>

      <h2>Members</h2>
      <ul>
        {% for user in project.member_users.all %}
          <li>{{ user }}</li>
        {% endfor %}
      </ul>
    </div>
    <br />
    <hr />

    <div class="checkchat">
      {% if user in project.member_users.all %}
        <!-- also need to check user is joined when submitting message -->
        <div class="chatparent">
          <h2>Group chat</h2>
          <p>
            <ul class="chat" id="chat">
              {% for message in project.message_set.all %}
                <li>
                  <hr />
                  {{ message.post_date }}<br />{{ message.poster }}: {{ message.text }}
                </li>
              {% endfor %}
              <br /> <br /> <br />
            </ul>
            <p>
              <form action="{% url 'project-detail-send-message' project.id %}" method="post" id="message" class="chatbox">
                {% csrf_token %}
                {{ forms.message }}
                <input type="submit" value="send" />
              </form>

        </div>

      {% endif %}

      <div class="checkparent" id="checklist">
        <h2>Checklist</h2>
        <ul class="detaillist">
          {% if user in project.member_users.all %}
            <form action="" method="post">
              {% csrf_token %}
              {% for item in forms.list.checks %}
                <li style="list-style-type: none; padding-top:1.5%">{{ item }}</li>
              {% endfor %}
            </form>
          {% else %}
            {% for item in project.checklistitem_set.all %}
              <li>
                {% if item.is_checked %}
                  ☑
                {% else %}
                  ☐
                {% endif %} {{ item.description }}
              </li>
            {% endfor %}
          {% endif %}
        </ul>
        {% if user in project.member_users.all %}
          <p>
            <form action="{% url 'project-detail-add-item' project.id %}" method="post" class="chatbox">
              {% csrf_token %}
              {{ forms.item }}
              <input type="submit" value="Add item" />
            </form>
          </p>
          <a class="linkbutton" href="{% url 'project-delete-checklist-items' project.id %}">Delete checklist items</a>
        {% endif %}
      </div>
    </div>

    <!--   <div class="send_message">
    <hr>
    <form action="/send_message/" method="post">
      <label for="message"></label>
      <input id="message" type="text" name="message" value="{{ current_message }}">
      <input type="submit" value="Send">
    </form>
  </div>   -->
    <div style="clear:both;">
      <h2>Comments</h2>
      <ul>
        {% for comment in project.comment_set.all %}
          <li id="commentlist" class="commentlist">
            <hr />
            <strong><a class="linkbutton" href="{{ comment.commenter.get_absolute_url }}">{{ comment.commenter }}</a></strong>, {{ comment.post_date }}
            <p>{{ comment.text }}</p>
          </li>
        {% endfor %}
        <hr />
        {% if user.is_authenticated%}
        <p>
          <form action="{% url 'project-detail-add-comment' project.id %}" method="post" id="comment">
            {% csrf_token %}
            {{ forms.comment }}
            <input type="submit" value="post" />
          </form>
        </p>
        {%endif%}
      </ul>
    </div>
  </div>
{% endblock %}

<!--   <form action="/projectboard/send_comment/" method="post" class = "">
  <label for="comment"></label>
  <input id="comment" type="text" name="comment" value="{{ current_comment }}" size="100">
  <input type="submit" value="post">
</form>     -->

projectboard/templates/projectboard/project_form.html
{% extends 'base.html' %}
{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <input type="submit" value="Submit" />
  </form>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCz__n-yYuMyDgr5OTwWpUQC6m9PbhxCLY&libraries=places&callback=Function.prototype"></script>
  <script>
    function initMap() {
        var latInput = document.getElementById('map-lat');
        var longInput = document.getElementById('map-long');
        var initialLat = {% if form.instance.lat %} {{form.instance.lat}} {% else %} 45.548349952852995 {% endif %};
        var initialLng = {% if form.instance.long %} {{form.instance.long}} {% else %} 13.742436210805522 {% endif %};

        var map = new google.maps.Map(document.getElementById('project-map'), {
            center: { lat: initialLat, lng: initialLng },
            zoom: 10
        });

        var marker = new google.maps.Marker({
            map: map,
            position: { lat: initialLat, lng: initialLng },
            draggable: true
        });

        latInput.value = initialLat;
        longInput.value = initialLng;

        google.maps.event.addListener(map, 'click', function (event) {
            // delete old marker if it exists
            if (marker) {
                marker.setMap(null);
            }

            marker = new google.maps.Marker({
                map: map,
                position: event.latLng,
                draggable: true
            });

            latInput.value = event.latLng.lat();
            longInput.value = event.latLng.lng();
        });
    }

    google.maps.event.addDomListener(window, 'load', initMap);
</script>


  <h2>Select location:</h2>
  <div id="project-map"></div>
{% endblock %}

projectboard/templates/projectboard/project_invites.html
{% extends 'base.html' %}

{% block content %}
  <h2>Invites</h2>
  {% if user_invites %}
    <ul>
      {% for invite in user_invites %}
        <li>
          {{ invite.inviting_user }} invited you to {{ invite.project }}
          <form method="post" action="{% url 'accept-invite' invite.id %}">
            {% csrf_token %}
            <button type="submit" name="action" value="accept">Accept</button>
            <button type="submit" name="action" value="delete">Delete</button>
          </form>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>You currently have no invites</p>
  {% endif %}
{% endblock %}

projectboard/templates/projectboard/project_list.html
{% extends "base.html" %}

{% block content %}
<h2>Projects</h2>
<form method="GET" action="{% url 'projects' %}">
    <input type="text" name="q" placeholder="Search projects...">
    <button type="submit">Search</button>
</form>
<hr>
    <ul class = "projectlist">
    {% for project in project_list %}
        <li class="project">
            <div class="projectcore">
            ({{ project.points }} point{{ project.points|pluralize }}) 
            
            <strong><a class="linkbutton" href="{{project.author_user.get_absolute_url}}">{{project.author_user}}</a>: </strong><a class="linkbutton" href="{{ project.get_absolute_url }}">{{ project.name }}</a>, posted on {{ project.post_date }}
            <p> Held at {{project.held_date}} </p>
                <p><i>"{{project.description}}"</i></p>
            </div>
            {%if project.checklistitem_set.all%}
            <!-- <div class = "checklist"> -->
                <ul class = "checklist">
                    {% for item in project.checklistitem_set.all %}
                        <li>{%if item.is_checked%}☑{%else%}☐{%endif%} {{item}}</li>
                    {% endfor %}
                </ul>
            <!-- </div> -->
            {%else%}
            {%endif%}
        </li>
        
    {% empty %}
        <p>No projects found!</p>
    {% endfor %}
    </ul>
</div>

{% endblock %}